services:
    - postgresql:latest
    
variables:
    POSTGRES_DB: lightcurvedb-test
    POSTGRES_USER: williamfong
    POSTGRES_PASSWORD: ""
    
before_script:
    apt-get update -qy
    apt-get install postgresql
    apt-get install python-dev python-pip
    pip install -r testrequirements.txt

run-test:
    script:
        tox