"""adding bls unique constraint by date

Revision ID: 0f8bba88ab28
Revises: 6dd622918a0b
Create Date: 2020-11-03 16:27:45.829833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8bba88ab28'
down_revision = '6dd622918a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_bls_runtime', 'bls', ['lightcurve_id', 'created_on'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_bls_runtime', 'bls', type_='unique')
    # ### end Alembic commands ###
