"""foreign key fix

Revision ID: 2da64f61b409
Revises: d325d7d7687a
Create Date: 2022-12-19 15:37:41.472064

"""
import sqlalchemy as sa

from alembic import op
from lightcurvedb import models as m

# revision identifiers, used by Alembic.
revision = "2da64f61b409"
down_revision = "d325d7d7687a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        m.Frame.__tablename__, sa.Column("tmp_id", sa.SmallInteger())
    )
    op.execute(
        f"UPDATE {m.Frame.__tablename__} "
        f"SET tmp_id = t.id FROM {m.FrameType.__tablename__} t "
        f"WHERE {m.Frame.__tablename__}.frame_type_id = t.name"
    )
    op.drop_constraint("unique_frame", m.Frame.__tablename__)
    op.drop_index("ix_frames_frame_type_id", m.Frame.__tablename__)
    op.drop_constraint(
        "frames_frame_type_id_fkey", "frames", type_="foreignkey"
    )
    op.drop_column(m.Frame.__tablename__, "frame_type_id")
    op.alter_column(
        m.Frame.__tablename__, "tmp_id", new_column_name="frame_type_id"
    )
    op.create_index(
        "ix_frames_frame_type_id", m.Frame.__tablename__, ["frame_type_id"]
    )
    op.create_unique_constraint(
        "unique_frame",
        m.Frame.__tablename__,
        ["frame_type_id", "orbit_id", "cadence", "camera", "ccd"],
    )
    op.create_foreign_key(
        None,
        "frames",
        "frametypes",
        ["frame_type_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "frames", type_="foreignkey")
    op.create_foreign_key(
        "frames_frame_type_id_fkey",
        "frames",
        "frametypes",
        ["frame_type_id"],
        ["name"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
