"""revising observation model

Revision ID: 2ffa104367ee
Revises: a8f3bcff7790
Create Date: 2020-05-30 02:16:19.845052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffa104367ee'
down_revision = 'a8f3bcff7790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_observations_camera'), 'observations', ['camera'], unique=False)
    op.create_index(op.f('ix_observations_ccd'), 'observations', ['ccd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_ccd'), table_name='observations')
    op.drop_index(op.f('ix_observations_camera'), table_name='observations')
    # ### end Alembic commands ###
