"""Adding metric models

Revision ID: 5961c1fadd12
Revises: cb18609410b0
Create Date: 2020-07-23 19:46:53.739422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5961c1fadd12'
down_revision = 'cb18609410b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qlpprocesses',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('id', sa.Integer(), sa.Sequence('qlpprocesses_id_seq', cache=100), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('job_version_major', sa.SmallInteger(), nullable=False),
    sa.Column('job_version_minor', sa.SmallInteger(), nullable=False),
    sa.Column('job_version_revision', sa.Integer(), nullable=False),
    sa.Column('additional_version_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qlpprocesses_additional_version_info'), 'qlpprocesses', ['additional_version_info'], unique=False)
    op.create_index(op.f('ix_qlpprocesses_job_type'), 'qlpprocesses', ['job_type'], unique=False)
    op.create_index(op.f('ix_qlpprocesses_job_version_major'), 'qlpprocesses', ['job_version_major'], unique=False)
    op.create_index(op.f('ix_qlpprocesses_job_version_minor'), 'qlpprocesses', ['job_version_minor'], unique=False)
    op.create_index(op.f('ix_qlpprocesses_job_version_revision'), 'qlpprocesses', ['job_version_revision'], unique=False)
    op.create_table('qlpalterations',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Sequence('qlpalterations_id_seq', cache=100), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('target_model', sa.String(length=255), nullable=False),
    sa.Column('_alteration_type', sa.String(length=255), nullable=False),
    sa.Column('n_altered_items', sa.BigInteger(), nullable=False),
    sa.Column('est_item_size', sa.BigInteger(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('_query', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], [u'qlpprocesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qlpalterations__alteration_type'), 'qlpalterations', ['_alteration_type'], unique=False)
    op.create_index(op.f('ix_qlpalterations__query'), 'qlpalterations', ['_query'], unique=False)
    op.create_index(op.f('ix_qlpalterations_est_item_size'), 'qlpalterations', ['est_item_size'], unique=False)
    op.create_index(op.f('ix_qlpalterations_n_altered_items'), 'qlpalterations', ['n_altered_items'], unique=False)
    op.create_index(op.f('ix_qlpalterations_target_model'), 'qlpalterations', ['target_model'], unique=False)
    op.create_index(op.f('ix_qlpalterations_time_end'), 'qlpalterations', ['time_end'], unique=False)
    op.create_index(op.f('ix_qlpalterations_time_start'), 'qlpalterations', ['time_start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qlpalterations_time_start'), table_name='qlpalterations')
    op.drop_index(op.f('ix_qlpalterations_time_end'), table_name='qlpalterations')
    op.drop_index(op.f('ix_qlpalterations_target_model'), table_name='qlpalterations')
    op.drop_index(op.f('ix_qlpalterations_n_altered_items'), table_name='qlpalterations')
    op.drop_index(op.f('ix_qlpalterations_est_item_size'), table_name='qlpalterations')
    op.drop_index(op.f('ix_qlpalterations__query'), table_name='qlpalterations')
    op.drop_index(op.f('ix_qlpalterations__alteration_type'), table_name='qlpalterations')
    op.drop_table('qlpalterations')
    op.drop_index(op.f('ix_qlpprocesses_job_version_revision'), table_name='qlpprocesses')
    op.drop_index(op.f('ix_qlpprocesses_job_version_minor'), table_name='qlpprocesses')
    op.drop_index(op.f('ix_qlpprocesses_job_version_major'), table_name='qlpprocesses')
    op.drop_index(op.f('ix_qlpprocesses_job_type'), table_name='qlpprocesses')
    op.drop_index(op.f('ix_qlpprocesses_additional_version_info'), table_name='qlpprocesses')
    op.drop_table('qlpprocesses')
    # ### end Alembic commands ###
