"""adding bls model

Revision ID: 6dd622918a0b
Revises: aac242ac5bb4
Create Date: 2020-11-02 18:13:11.740235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6dd622918a0b"
down_revision = "aac242ac5bb4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bls",
        sa.Column(
            "created_on",
            sa.DateTime(),
            server_default=sa.text(u"now()"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("lightcurve_id", sa.BigInteger(), nullable=True),
        sa.Column("astronet_score", sa.Float(), nullable=True),
        sa.Column("astronet_version", sa.String(length=256), nullable=True),
        sa.Column(
            "runtime_parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("period", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "transit_depth", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.Column(
            "transit_duration", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.Column(
            "planet_radius", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.Column(
            "planet_radius_error",
            postgresql.DOUBLE_PRECISION(),
            nullable=False,
        ),
        sa.Column("points_pre_transit", sa.Integer(), nullable=False),
        sa.Column("points_in_transit", sa.Integer(), nullable=False),
        sa.Column("points_post_transit", sa.Integer(), nullable=False),
        sa.Column("transits", sa.Integer(), nullable=False),
        sa.Column(
            "transit_shape", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.Column(
            "transit_center", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.Column(
            "duration_rel_period",
            postgresql.DOUBLE_PRECISION(),
            nullable=False,
        ),
        sa.Column("rednoise", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column("whitenoise", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "signal_to_noise", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.Column(
            "signal_to_pinknoise",
            postgresql.DOUBLE_PRECISION(),
            nullable=False,
        ),
        sa.Column("sde", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column("sr", postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "period_inv_transit", postgresql.DOUBLE_PRECISION(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bls_astronet_score"), "bls", ["astronet_score"], unique=False
    )
    op.create_index(
        op.f("ix_bls_lightcurve_id"), "bls", ["lightcurve_id"], unique=False
    )
    op.create_index(op.f("ix_bls_period"), "bls", ["period"], unique=False)
    op.create_index(
        op.f("ix_bls_planet_radius"), "bls", ["planet_radius"], unique=False
    )
    op.create_index(
        op.f("ix_bls_runtime_parameters"),
        "bls",
        ["runtime_parameters"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_bls_signal_to_noise"),
        "bls",
        ["signal_to_noise"],
        unique=False,
    )
    op.create_index(op.f("ix_bls_transits"), "bls", ["transits"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bls_transits"), table_name="bls")
    op.drop_index(op.f("ix_bls_signal_to_noise"), table_name="bls")
    op.drop_index(op.f("ix_bls_runtime_parameters"), table_name="bls")
    op.drop_index(op.f("ix_bls_planet_radius"), table_name="bls")
    op.drop_index(op.f("ix_bls_period"), table_name="bls")
    op.drop_index(op.f("ix_bls_lightcurve_id"), table_name="bls")
    op.drop_index(op.f("ix_bls_astronet_score"), table_name="bls")
    op.drop_table("bls")
    # ### end Alembic commands ###
