"""array_model

Revision ID: 828a1343876c
Revises: f127fed968b3
Create Date: 2022-10-04 13:58:44.692403

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "828a1343876c"
down_revision = "f127fed968b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "array_orbit_lightcurves",
        sa.Column(
            "created_on",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tic_id", sa.BigInteger(), nullable=True),
        sa.Column("camera", sa.SmallInteger(), nullable=True),
        sa.Column("ccd", sa.SmallInteger(), nullable=True),
        sa.Column("orbit_id", sa.Integer(), nullable=True),
        sa.Column("aperture_id", sa.SmallInteger(), nullable=True),
        sa.Column("lightcurve_type_id", sa.SmallInteger(), nullable=True),
        sa.Column(
            "cadences",
            postgresql.ARRAY(sa.BigInteger(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "barycentric_julian_dates",
            postgresql.ARRAY(sa.Float(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "data",
            postgresql.ARRAY(postgresql.DOUBLE_PRECISION(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "errors",
            postgresql.ARRAY(postgresql.DOUBLE_PRECISION(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "x_centroids",
            postgresql.ARRAY(sa.Float(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "y_centroids",
            postgresql.ARRAY(sa.Float(), dimensions=1),
            nullable=True,
        ),
        sa.Column(
            "quality_flags",
            postgresql.ARRAY(sa.Integer(), dimensions=1),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["aperture_id"],
            ["apertures.id"],
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_type_id"],
            ["lightcurvetypes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"], ["orbits.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tic_id",
            "camera",
            "ccd",
            "orbit_id",
            "aperture_id",
            "lightcurve_type_id",
            name="unique_array_lightcurve_constraint",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("array_orbit_lightcurves")
    # ### end Alembic commands ###
