"""empty message

Revision ID: 85a99e8a16dd
Revises: d101c424c39e
Create Date: 2021-10-26 13:33:03.186894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85a99e8a16dd'
down_revision = 'd101c424c39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bls', sa.Column('sector', sa.SmallInteger(), nullable=True))
    op.drop_index('ix_bls_astronet_score', table_name='bls')
    op.create_index(op.f('ix_bls_sector'), 'bls', ['sector'], unique=False)
    op.drop_column('bls', 'astronet_version')
    op.drop_column('bls', 'astronet_score')
    # ### end Alembic commands ###


def downgrade():
    op.add_column('bls', sa.Column('astronet_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bls', sa.Column('astronet_version', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bls_sector'), table_name='bls')
    op.create_index('ix_bls_astronet_score', 'bls', ['astronet_score'], unique=False)
    op.drop_column('bls', 'sector')
    # ### end Alembic commands ###
