"""adding lightpoint model

Revision ID: 90c9fd1a4c11
Revises: a494112e4f27
Create Date: 2020-02-12 10:09:01.755007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, DropSequence

# revision identifiers, used by Alembic.
revision = '90c9fd1a4c11'
down_revision = 'a494112e4f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightpoints',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=False),
    sa.Column('barycentric_julian_date', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('error', postgresql.DOUBLE_PRECISION(), nullable=True),
    sa.Column('x_centroid', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('y_centroid', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('quality_flag', sa.Integer(), nullable=False),
    sa.Column('lightcurve_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Sequence('lightpoints_pk_table'), nullable=False),
    sa.ForeignKeyConstraint(['lightcurve_id'], ['lightcurves.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lightcurve_id', 'cadence', name='lc_cadence_unique')
    )
    op.create_index(op.f('ix_lightpoints_barycentric_julian_date'), 'lightpoints', ['barycentric_julian_date'], unique=False)
    op.create_index(op.f('ix_lightpoints_lightcurve_id'), 'lightpoints', ['lightcurve_id'], unique=False)
    op.drop_column('lightcurves', 'barycentric_julian_date')
    op.drop_column('lightcurves', 'flux')
    op.drop_column('lightcurves', 'quality_flags')
    op.drop_column('lightcurves', 'flux_err')
    op.drop_column('lightcurves', 'x_centroids')
    op.drop_column('lightcurves', 'y_centroids')
    op.drop_column('lightcurves', 'cadences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lightcurves', sa.Column('cadences', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.add_column('lightcurves', sa.Column('y_centroids', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False))
    op.add_column('lightcurves', sa.Column('x_centroids', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False))
    op.add_column('lightcurves', sa.Column('flux_err', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False))
    op.add_column('lightcurves', sa.Column('quality_flags', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.add_column('lightcurves', sa.Column('flux', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False))
    op.add_column('lightcurves', sa.Column('barycentric_julian_date', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_lightpoints_lightcurve_id'), table_name='lightpoints')
    op.drop_index(op.f('ix_lightpoints_barycentric_julian_date'), table_name='lightpoints')
    op.drop_table('lightpoints')
    op.execute(DropSequence('lightpoints_pk_table'))
    # ### end Alembic commands ###
