"""Adding FK indices on Frames

Revision ID: cb18609410b0
Revises: 95672973dbdd
Create Date: 2020-07-01 09:28:15.341495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb18609410b0'
down_revision = '95672973dbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_frames_frame_type_id'), 'frames', ['frame_type_id'], unique=False)
    op.create_index(op.f('ix_frames_orbit_id'), 'frames', ['orbit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frames_orbit_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_frame_type_id'), table_name='frames')
    # ### end Alembic commands ###
