"""updating bls model

Revision ID: d101c424c39e
Revises: e8b0eecf8359
Create Date: 2021-06-25 12:38:19.522316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd101c424c39e'
down_revision = 'e8b0eecf8359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bls', sa.Column('tce_n', sa.SmallInteger(), nullable=True))
    op.execute(
        "UPDATE bls SET tce_n TO 1"
    )
    op.alter_column("bls", "tce_n", nullable=False)
    op.drop_constraint('unique_bls_runtime', 'bls', type_='unique')
    op.create_unique_constraint('unique_bls_runtime', 'bls', ['lightcurve_id', 'sector', 'tce_n'])
    op.create_index(op.f('ix_bls_tce_n'), 'bls', ['tce_n'], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bls_tce_n'), table_name='bls')
    op.drop_constraint('unique_bls_runtime', 'bls', type_='unique')
    op.create_unique_constraint('unique_bls_runtime', 'bls', ['lightcurve_id', 'created_on'])
    op.drop_column('bls', 'tce_n')
    # ### end Alembic commands ###
