"""tag refactor

Revision ID: d325d7d7687a
Revises: 7910ebee4ab2
Create Date: 2022-12-14 23:25:25.126703

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d325d7d7687a"
down_revision = "7910ebee4ab2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bls_association_table",
        sa.Column("bls_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "bls_association_table",
        sa.Column("tag_id", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "bls_association_table_tag_fkey",
        "bls_association_table",
        type_="foreignkey",
    )
    op.drop_constraint(
        "bls_association_table_bls_fkey",
        "bls_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "bls_association_table", "bls", ["bls_id"], ["id"]
    )
    op.create_foreign_key(
        None, "bls_association_table", "bls_tags", ["tag_id"], ["id"]
    )
    op.drop_column("bls_association_table", "tag")
    op.drop_column("bls_association_table", "bls")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bls_association_table",
        sa.Column("bls", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bls_association_table",
        sa.Column("tag", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "bls_association_table", type_="foreignkey")
    op.drop_constraint(None, "bls_association_table", type_="foreignkey")
    op.create_foreign_key(
        "bls_association_table_bls_fkey",
        "bls_association_table",
        "bls",
        ["bls"],
        ["id"],
    )
    op.create_foreign_key(
        "bls_association_table_tag_fkey",
        "bls_association_table",
        "bls_tags",
        ["tag"],
        ["id"],
    )
    op.drop_column("bls_association_table", "tag_id")
    op.drop_column("bls_association_table", "bls_id")
    # ### end Alembic commands ###
