"""adding sector

Revision ID: e2ecdfc1a06f
Revises: 0f8bba88ab28
Create Date: 2020-11-03 18:54:09.562230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ecdfc1a06f'
down_revision = '0f8bba88ab28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bls', sa.Column('sector', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bls_sector'), 'bls', ['sector'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bls_sector'), table_name='bls')
    op.drop_column('bls', 'sector')
    # ### end Alembic commands ###
