"""creating partition catalog_tables

Revision ID: e8b0eecf8359
Revises: d308eb3931f9
Create Date: 2021-04-02 12:43:26.449072

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e8b0eecf8359"
down_revision = "d308eb3931f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partition_tracks",
        sa.Column(
            "created_on",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("oid", sa.Integer(), nullable=True),
        sa.Column("tracker_type", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_partition_tracks_model"),
        "partition_tracks",
        ["model"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partition_tracks_oid"),
        "partition_tracks",
        ["oid"],
        unique=True,
    )
    op.create_index(
        op.f("ix_partition_tracks_tracker_type"),
        "partition_tracks",
        ["tracker_type"],
        unique=False,
    )
    op.create_table(
        "ranged_partition_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("min_range", sa.Integer(), nullable=True),
        sa.Column("max_range", sa.Integer(), nullable=True),
        sa.CheckConstraint("max_range > min_range", name="range_validity"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["partition_tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ranged_partition_tracks_max_range"),
        "ranged_partition_tracks",
        ["max_range"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ranged_partition_tracks_min_range"),
        "ranged_partition_tracks",
        ["min_range"],
        unique=False,
    )

    op.drop_table("observations_orbit_13")
    op.drop_table("observations_orbit_17")
    op.drop_table("observations_orbit_10")
    op.drop_table("observations_orbit_69")
    op.drop_table("observations_orbit_12")
    op.drop_table("observations_orbit_30")
    op.drop_table("observations_orbit_11")
    op.drop_table("observations_orbit_22")
    op.drop_table("observations_orbit_33")
    op.drop_table("observations_orbit_66")
    op.drop_table("observations_orbit_48")
    op.drop_table("observations_orbit_28")
    op.drop_table("observations_orbit_62")
    op.drop_table("observations_orbit_16")
    op.drop_table("observations_orbit_46")
    op.drop_table("observations_orbit_74")
    op.drop_table("observations_orbit_18")
    op.drop_table("observations_orbit_64")
    op.drop_table("observations_orbit_77")
    op.drop_table("observations_orbit_44")
    op.drop_table("observations_orbit_78")
    op.drop_table("observations_orbit_39")
    op.drop_table("observations_orbit_47")
    op.drop_table("observations_orbit_24578")
    op.drop_table("observations_orbit_25")
    op.drop_table("observations_orbit_9")
    op.drop_table("observations_orbit_51")
    op.drop_table("observations_orbit_60")
    op.drop_table("observations_orbit_45")
    op.drop_table("observations_orbit_42")
    op.drop_table("observations_orbit_72")
    op.drop_table("observations_orbit_56")
    op.drop_table("observations_orbit_53")
    op.drop_table("observations_orbit_76")
    op.drop_table("observations_orbit_55")
    op.drop_table("observations_orbit_36")
    op.drop_table("observations_orbit_50")
    op.drop_table("observations_orbit_61")
    op.drop_table("observations_orbit_63")
    op.drop_table("observations_orbit_37")
    op.drop_table("observations_orbit_40")
    op.drop_table("observations_orbit_20")
    op.drop_table("observations_orbit_67")
    op.drop_table("observations_orbit_32")
    op.drop_table("observations_orbit_14")
    op.drop_table("observations_orbit_38")
    op.drop_table("observations_orbit_59")
    op.drop_table("observations_orbit_31")
    op.drop_table("observations_orbit_27")
    op.drop_table("observations_orbit_70")
    op.drop_table("observations_orbit_26")
    op.drop_table("observations_orbit_43")
    op.drop_table("observations_orbit_23")
    op.drop_table("observations_orbit_49")
    op.drop_table("observations_orbit_79")
    op.drop_table("observations_orbit_41")
    op.drop_table("observations_orbit_19")
    op.drop_table("observations_orbit_68")
    op.drop_table("observations_orbit_54")
    op.drop_table("observations_orbit_24580")
    op.drop_table("observations_orbit_73")
    op.drop_table("observations_orbit_21")
    op.drop_table("observations_orbit_29")
    op.drop_table("observations_orbit_52")
    op.drop_table("observations_orbit_34")
    op.drop_table("observations_old")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observations_orbit_65",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_24",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_15",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_58",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_71",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_35",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_57",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_75",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_old",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_34",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_52",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_29",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_21",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_73",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_24580",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_54",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_68",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_19",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_41",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_79",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_49",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_23",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_43",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_26",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_70",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_27",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_31",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_59",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_38",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_14",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_32",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_67",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_20",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_40",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_37",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_63",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_61",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_50",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_36",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_55",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_76",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_53",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_56",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_72",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_42",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_45",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_60",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_51",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_9",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_25",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_24578",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_47",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_39",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_78",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_44",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_77",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_64",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_18",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_74",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_46",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_16",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_62",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_28",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_48",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_66",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_33",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_22",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_11",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_30",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_12",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_69",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_10",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_17",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_table(
        "observations_orbit_13",
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lightcurve_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "camera", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.Column("ccd", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "orbit_id", sa.SMALLINT(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lightcurve_id"],
            ["lightcurves.id"],
            name="observation_lightcurve_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orbit_id"],
            ["orbits.id"],
            name="observation_orbit_fkey",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.drop_index(
        op.f("ix_ranged_partition_tracks_min_range"),
        table_name="ranged_partition_tracks",
    )
    op.drop_index(
        op.f("ix_ranged_partition_tracks_max_range"),
        table_name="ranged_partition_tracks",
    )
    op.drop_table("ranged_partition_tracks")
    op.drop_index(
        op.f("ix_partition_tracks_tracker_type"), table_name="partition_tracks"
    )
    op.drop_index(
        op.f("ix_partition_tracks_oid"), table_name="partition_tracks"
    )
    op.drop_index(
        op.f("ix_partition_tracks_model"), table_name="partition_tracks"
    )
    op.drop_table("partition_tracks")
    # ### end Alembic commands ###
