"""temporary observation table for JIRA 194

Revision ID: eee1e61ac19b
Revises: e2ecdfc1a06f
Create Date: 2021-02-23 18:10:02.503072

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "eee1e61ac19b"
down_revision = "e2ecdfc1a06f"
branch_labels = None
depends_on = None

TARGET_TABLE = "complete_observations"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        TARGET_TABLE,
        sa.Column(
            "created_on",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "lightcurve_id",
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "camera", sa.SmallInteger(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "ccd", sa.SmallInteger(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "orbit_id", sa.SmallInteger(), autoincrement=False, nullable=False
        ),
        postgresql_partition_by="list(orbit_id)",
    )
    op.create_primary_key(
        "observation_pk",
        TARGET_TABLE,
        ["lightcurve_id", "camera", "ccd", "orbit_id"],
    )
    op.create_index(
        "observation_creation_idx",
        TARGET_TABLE,
        ["created_on"],
        postgresql_using="brin",
    )
    op.create_foreign_key(
        "observation_lightcurve_fkey",
        TARGET_TABLE,
        "lightcurves",
        ["lightcurve_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "observation_orbit_fkey",
        TARGET_TABLE,
        "orbits",
        ["orbit_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "observation_orbit_fkey", TARGET_TABLE, type_="foreignkey"
    )
    op.drop_constraint(
        "observation_lightcurve_fkey", TARGET_TABLE, type_="foreignkey"
    )
    op.drop_index("observation_creation_idx", TARGET_TABLE)
    op.drop_table(TARGET_TABLE)
    # ### end Alembic commands ###
