from sqlalchemy import Column
from sqlalchemy.dialects import postgresql as psql
from sqlalchemy.schema import CreateColumn
from sqlalchemy.ext.compiler import compiles


def high_precision_column(precision=None, asdecimal=False, **column_args):
    return Column(
        psql.DOUBLE_PRECISION(precision=precision, asdecimal=asdecimal),
        **column_args
    )


@compiles(CreateColumn, "postgresql")
def use_identity(element, compiler, **kw):
    text = compiler.visit_create_column(element, **kw)
    text = text.replace("SERIAL", "INT GENERATED BY DEFAULT AS IDENTITY")
    return text
