name: Commit Lint

on:
  pull_request:
    branches: [master, main, staging]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install commitizen
      - run: cz check --rev-range origin/${{ github.base_ref }}..HEAD
